### ISSUE TITLE
access the view object from outside the component?

### ISSUE THREAD

**Issue by dmccallie** [touchifyapp/svelte-codemirror-editor#10]
Hello, 

Thank you for releasing this very helpful library. I am new to CodeMirror (and Svelte) and your easy to follow code has been a huge help in understanding how to use CodeMirror.

I have a naïve user question - I'd like to be able to manipulate the contents of the view from outside of the control itself. I'd like to be able to do something like what is described in the documentation here https://codemirror.net/examples/change/

For example, allow the user to insert a markdown reference to an image after popping up a file selector dialog, and then inserting the proper URL at the current cursor location. (I'm using the editor in markdown language mode.) Something like:

```ts
// Insert markdown image placeholder at the current edit position of the document
view.dispatch({
  changes: {from: curPos, insert: "![image_name](image_url)"}
})
```
My question - is there any way to get access to the ` view ` object from outside the control?

Thanks in advance!

**Comment by zopsicle** [comment]
You can write a [view plugin](https://codemirror.net/docs/ref/#view.ViewPlugin) and specify it as an extension:

```svelte
<script lang="ts">

    import CodeMirror from "svelte-codemirror-editor";
    import { ViewPlugin } from "@codemirror/view";

    const extensions = [
        ViewPlugin.define(view => {
            console.log(view);
            return {};
        }),
    ];

</script>

<CodeMirror {extensions} />
```

**Comment by SomaticIT** [comment]
Thanks @chloekek,
I think it's the best solution.
