### ISSUE TITLE
sveltekit error: Internal server error: Cannot find module 'codemirror' imported from '/node_modules/svelte-codemirror-editor/CodeMirror.svelte

### ISSUE THREAD

**Issue by Blumed** [touchifyapp/svelte-codemirror-editor#11]
Downloaded the latest sveltekit today. Imported your script and followed your sveltekit instructions, which worked great. I did have to install `@codemirror/lang-javascript` separately, which was something I didn't see mentioned in your README. When I run the package I am getting the error in the title. Your index.js looks right and when I hover over `Codemirror` in VSCode it shows the correct import name. Any ideas why this is happening?

**Comment by Blumed** [comment]
I was able to get this to work by adding codemirror to the project. One thing I would also point out using sveltekit is that you can install all the dependancies as dev dependancies. None of them need to be added as dependancies. Also, you don't need to do anything different for this package to work in `vite.config.ts`.

**Comment by Arro** [comment]
@Blumed do you remember anything more you did to get this to go away?  I have this in my vscode and it's driving me batty.

**Comment by Blumed** [comment]
> @Blumed do you remember anything more you did to get this to go away?  I have this in my vscode and it's driving me batty.

@Arro I did end up getting it to work. Here is the file I am initializing it in so you can follow my example: https://github.com/Blumed/make-bookmarklets/blob/main/src%2Flib%2Fcomponents%2Feditors%2Fjs-editor.svelte

Here is my package.json: https://github.com/Blumed/make-bookmarklets/blob/main/package.json

It has been a long time but I think I ended up importing dependencies which I didn't think I had to.

Hope this helps.
