### ISSUE TITLE
How to toggle options after editor is created?

### ISSUE THREAD

**Issue by Jakobud** [touchifyapp/svelte-codemirror-editor#14]
I want to be able to change themes, change line numbers, change word wrapping, etc. How do I do this?

**Comment by SomaticIT** [comment]
Hello,

You should be able to update all options after editor is created by using usual svelte syntax.
cf: https://github.com/touchifyapp/svelte-codemirror-editor#custom-theme

Does it work?
If not, can you provide a reproducible code?

Thanks,
