### ISSUE TITLE
don't debounce 'handle_change'

### ISSUE THREAD

**Issue by Jan540** [touchifyapp/svelte-codemirror-editor#15]
In the current implementation, the editor value only changes when the user stops typing.
I understand why you'd want this, but I'd like to at least be able to toggle it.

My suggestion would be to either remove the debounce altogether and let the user implement it themselves, or to make it toggleable using a prop.

**Comment by dit7ya** [comment]
@Jan540 Could you please tell me how this issue was resolved? I have stumbled upon something which I believe is caused by the `debounce` but just want to make sure removing it is safe.

**Comment by Jan540** [comment]
I just yoinked the code, created the component manually and removed the `debounce`. Seems to be safe, I have not run into any issues.

**Comment by dit7ya** [comment]
Thanks :+1: .
