### ISSUE TITLE
Possibility of adding custom decorations, tooltips, click handlers, context menus

### ISSUE THREAD

**Issue by hammonia-io** [touchifyapp/svelte-codemirror-editor#16]
Hello,
ist it possible to use custom
- decorations
- tooltips
- click handlers

with the svelte editor, or would i need to use codemirror pure?

**Comment by SomaticIT** [comment]
Hello,

You can customize the CodeMirror setup using custom extensions:
```svelte
<CodeMirror {...} extensions={[my_extension1, my_extension2]} />
```

**Comment by keanesnow98** [comment]
Hello, @SomaticIT !
If I need to write a text from current caret in the editor, how can I do it?

**Comment by SomaticIT** [comment]
IMHO, the best way to write a text from current caret should be to create an (inlined) extension that reacts on a keyboard shortcut and create a transaction based on the current selection.

You can find below some documentation that can help:
- Keyboard-based extension: https://codemirror.net/docs/guide/#extension
- Selection-based transaction: https://codemirror.net/docs/guide/#selection
- Commands: https://codemirror.net/docs/guide/#commands

```svelte
<script>
import { keymap } from "@codemirror/view";

function my_ext() {
  return keymap.of([{
    key: "Ctrl+Alt+T",
    run(view) {
      const transaction = view.state.update(view.state.replaceSelection("MY_CONTENT"));
      view.dispatch(transaction);
    }
  }])
}
</script>

<CodeMirror {...} extensions={[my_ext()]} />
```

**Comment by keanesnow98** [comment]
> IMHO, the best way to write a text from current caret should be to create an (inlined) extension that reacts on a keyboard shortcut and create a transaction based on the current selection.
> 
> You can find below some documentation that can help:
> 
> * Keyboard-based extension: https://codemirror.net/docs/guide/#extension
> * Selection-based transaction: https://codemirror.net/docs/guide/#selection
> * Commands: https://codemirror.net/docs/guide/#commands
> 
> ```svelte
> <script>
> import { keymap } from "@codemirror/view";
> 
> function my_ext() {
>   return keymap.of([{
>     key: "Ctrl+Alt+T",
>     run(view) {
>       const transaction = view.state.update(view.state.replaceSelection("MY_CONTENT"));
>       view.dispatch(transaction);
>     }
>   }])
> }
> </script>
> 
> <CodeMirror {...} extensions={[my_ext()]} />
> ```

Thanks very much @SomaticIT 
I will try right away!

**Comment by SomaticIT** [comment]
👍 let me know
