### ISSUE TITLE
Is there are way to access EditorState?

### ISSUE THREAD

**Issue by gavinmcfarland** [touchifyapp/svelte-codemirror-editor#19]
Firstly. Thank you for sharing this Svelte component. It makes it a lot easier to use CodeMirror out of the box.

I'm trying to add my own autocomplete suggestions but I'm struggling to understand CodeMirror's documentation. If I understand it correctly, EditorState is needed to pass through as a CompletionContext. If this is correct is there a way to get the EditorState from svelte-codemirror-editor?

https://codemirror.net/docs/ref/#autocomplete.CompletionContext

**Comment by SomaticIT** [comment]
Hello,

If I remember correctly, you never have to instanciate the `CompletionContext` class by yourself.
CodeMirror is providing you the `CompletionContext` instance to your language module.

**Comment by gavinmcfarland** [comment]
Ah ok, thanks. I'll have another look. Do you know what this might happen to look like? I'm guessing maybe something like this now?

```js
<script>
function myCompletions(context) {
    let word = context.matchBefore(/\w*/)
    if (word.from == word.to && !context.explicit) {
        return null
    }
    return {
        from: word.from,
            options: [
                {label: "match", type: "keyword"},
                {label: "hello", type: "variable", info: "(World)"},
                {label: "magic", type: "text", apply: "⠁⭒*.✩.*⭒⠁", detail: "macro"}
            ]
      }
}
</script>

<CodeMirror
    bind:value={value}
    lang={javascript().data.of({
        autocomplete: myCompletions
    })}
    extensions={[autocomplete()]}
/>
```

**Comment by SomaticIT** [comment]
Sorry for my late response.
It seems correct.

Did it work for you?

**Comment by SomaticIT** [comment]
For information, PR #31 allows you to get access to `EditorView` using `ready` event.
Any news to share for your use case?

**Comment by gavinmcfarland** [comment]
Hi. Thanks for letting me know about this. The code I proposed didn't work unfortunately so I created an instance from scratch. When I get chance I'll try the new event. Thanks you!

**Comment by yashash-pugalia** [comment]
@gavinmcfarland could you please share the code if you could get that to work.

**Comment by gavinmcfarland** [comment]
Sure, I created it from scratch. Maybe it'll help you.

https://github.com/gavinmcfarland/figma-vite-svelte-codemirror-example/blob/main/src/App.svelte

**Comment by yashash-pugalia** [comment]
Thanks @gavinmcfarland I am just trying to disable autocomplete altogether if you could help.

**Comment by yashash-pugalia** [comment]
Thanks a lot Gavin, really appreciate it.
