### ISSUE TITLE
Using legacy modes

### ISSUE THREAD

**Issue by beeb** [touchifyapp/svelte-codemirror-editor#2]
I am trying to use [legacy modes](https://github.com/codemirror/legacy-modes) to enable YAML support.

Doing the following in my component:

```typescript
import { StreamLanguage } from '@codemirror/language'
import { yaml } from '@codemirror/legacy-modes/mode/yaml'
const yamlExtension = StreamLanguage.define(yaml)
```

and then passing `extensions={[yamlExtension]}` to the `CodeMirror` component.

This results in the following error in SvelteKit:

```
Uncaught (in promise) Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.
    at inner (index.js?v=9809bf15:2014:23)
    at inner (index.js?v=9809bf15:1989:17)
    at flatten (index.js?v=9809bf15:2018:5)
    at Configuration.resolve (index.js?v=9809bf15:1926:25)
    at EditorState.create (index.js?v=9809bf15:2753:43)
    at create_editor_state (CodeMirror.svelte:86:24)
    at create_editor_view (CodeMirror.svelte:46:16)
    at CodeMirror.svelte:40:23
    at run (index.mjs:18:12)
    at Array.map (<anonymous>)
```

Actually, this happens as soon as I install `@codemirror/language` even if I don't import it anywhere. Any idea how I can add YAML support to the editor?

Thanks!

**Comment by SomaticIT** [comment]
Hello,

If you are working with `vite` or `sveltekit`, you have to exclude all codemirror dependant module from optimization to avoid state duplication:

```javascript
// vite.config.js
const config = {
    //...
    optimizeDeps: {
        exclude: ["codemirror", "@codemirror/language", "@codemirror/legacy-modes/mode/yaml"],
    },
    //...
}
```

**Comment by beeb** [comment]
I should have read better... Sorry!

**Comment by SomaticIT** [comment]
No problem. Thanks

**Comment by danawoodman** [comment]
@beeb how did you actually set the language mode once you got passing the language mode extensions in?
