### ISSUE TITLE
The example in README.md cannot compile because `@codemirror/lang-javascript` is missing

### ISSUE THREAD

**Issue by vincenzoml** [touchifyapp/svelte-codemirror-editor#22]
Trying to run the example provided in README.md I get:

```
[plugin:vite:import-analysis] Failed to resolve import "@codemirror/lang-javascript" from "src/components/SpecEditor.svelte". Does the file exist?
19 |  import "svelte/internal/disclose-version";
20 |  import CodeMirror from "svelte-codemirror-editor";
21 |  import { javascript } from "@codemirror/lang-javascript";
   |                              ^
22 |  const file = "src/components/SpecEditor.svelte";
```

**Comment by SomaticIT** [comment]
Hi,
Thank you for your issue.
Did you install the package : `npm install @codemirror/lang-javascript`?

**Comment by vincenzoml** [comment]
Yes I did! It ought to be better to mention this in the same README 
where the example is presented, it is confusing for those who have not 
used codemirror before.



------ Messaggio originale ------
Da "Maxime LUCE" ***@***.***>
A "touchifyapp/svelte-codemirror-editor" 
***@***.***>
Cc "Vincenzo Ciancia" ***@***.***>; "Author" 
***@***.***>
Data 21/09/2023 12:18:19
Oggetto Re: [touchifyapp/svelte-codemirror-editor] The example in 
README.md cannot compile because ***@***.***/lang-javascript` is 
missing (Issue #22)

**Comment by firehudson** [comment]
@vincenzoml just follow the documentation and add followign to `vite.config.ts` 
https://github.com/touchifyapp/svelte-codemirror-editor?tab=readme-ov-file#usage-with-vite--svelte-kit

```ts
// vite.config.js
const config = {
    //...
    optimizeDeps: {
        exclude: ["codemirror", "@codemirror/language-javascript" /* ... */],
    },
    //...
}
```

**Comment by SomaticIT** [comment]
Thanks @firehudson
