### ISSUE TITLE
Option to disable on:change debouncing?

### ISSUE THREAD

**Issue by Pjaerr** [touchifyapp/svelte-codemirror-editor#24]
👋  Can we provide an option to disable the debouncing that happens on:change? I want to use the input in real-time to render something else but it isn't possible the way the code currently is.

**Comment by SomaticIT** [comment]
Hello @Pjaerr,

Thank you for reporting this issue.
We added a new option `nodebounce` in `v1.2.0`.

You can now do:
```svelte
<CodeMirror bind:value nodebounce />
```

**Comment by Pjaerr** [comment]
@SomaticIT That's brilliant, thanks for that 🙌
