### ISSUE TITLE
optimizeDeps exludes didn't work

### ISSUE THREAD

**Issue by MaxBittker** [touchifyapp/svelte-codemirror-editor#27]
Cheers for the great component. Wanted to point out this issue I hit that might help others, and possibly the docs should be updated. 

In my vite.config.js, I had to do this:

```    
optimizeDeps: {
        exclude: ["svelte-codemirror-editor", "codemirror", "@codemirror/lang-javascript" /* ... */],
    },
 ```

because:
```
    optimizeDeps: {
        exclude: ["codemirror", "@codemirror/language-javascript" /* ... */],
    },
```

did not work, and I still had this error :

```index.js:2044 Uncaught (in promise) Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instanceof checks.```

For reference:

```
"svelte-codemirror-editor": "^1.2.0",
"@codemirror/lang-javascript": "^6.2.1",
"codemirror": "^6.0.1",
"@sveltejs/adapter-auto": "^3.0.0",
"@sveltejs/adapter-static": "^3.0.1",
"@sveltejs/kit": "^2.0.0",
"@sveltejs/vite-plugin-svelte": "^3.0.0",
"svelte": "^4.2.7",
"svelte-check": "^3.6.0",
"tailwindcss": "^3.4.0",
"tslib": "^2.4.1",
"typescript": "^5.0.0",
"vite": "^5.0.3"
```

**Comment by tsdexter** [comment]
Same, thank you!

**Comment by SomaticIT** [comment]
You're right when using vite 5+.
I updated the documentation.
Thank you
