### ISSUE TITLE
Toggle line numbers?

### ISSUE THREAD

**Issue by danawoodman** [touchifyapp/svelte-codemirror-editor#3]
Loving the library!

Any way to easily toggle line numbers on/off?

I've looked at the code mirror docs and they're perhaps the hardest to follow docs I've seen in my entire career 😅

Any tips would be greatly appreciated 🤩

PS: same question for the "collapse caret" icon

**Comment by SomaticIT** [comment]
Hello,

Thank you for your comment 👍!

Unfortunately, the `lineNumber` extension is part of the `basicSetup` package.
You can replace the the `basicSetup` extension by providing manually each of the included extensions.

You can find the included extensions here: https://github.com/codemirror/basic-setup/blob/main/src/codemirror.ts

Here is an example to setup this component without basic setup:

```svelte
<script>
import CodeMirror from "svelte-codemirror-editor";
import { myCustomSetup } from "$lib/codemirror/myextensions";
</script>

<CodeMirror basic={false} extensions={myCustomSetup} />
```

We will investigate in making this easier in the next major release of this library.

Hope this helps!
