### ISSUE TITLE
SvelteKit setup hint is outdated

### ISSUE THREAD

**Issue by TimJentzsch** [touchifyapp/svelte-codemirror-editor#5]
The README claims the following about disable dependency optimization for SvelteKit:

> Note: on svelte-kit, this parameter is under the `kit` property.

As of recently, this is not true anymore and will not compile:

```
error when starting dev server:
Error: Unexpected option config.kit.optimizeDeps
```

Instead, the `optimizeDeps` needs to be placed in the `vite.config.ts` file instead of `svelte.config.js`.

I think this change was detailed in some release announcement, but unfortunately I cannot find it anymore.

**Comment by SomaticIT** [comment]
Hello @TimJentzsch,

Thank you for your feedback.
You're right, the documentation was not updated since `svelte-kit` was updated to become a `vite` plugin.

I updated the documentation to match this change.
