### ISSUE TITLE
Entering any props to the CodeMirror component (e.g. lang={javascript()}) throws an exception

### ISSUE THREAD

**Issue by DaleSparrow** [touchifyapp/svelte-codemirror-editor#6]
This svelte component works great in my sveltekit project, however I cannot use any of the theme, language or other options as it throws the following error:

Error: Unrecognized extension value in extension set ([object Object]). This sometimes happens because multiple instances of @codemirror/state are loaded, breaking instance of checks.

I have scraped the web to try and figure out how I could fix it but I fear my surface level knowledge will just jippo it in a non-maintainable way.

Here are some links I found:
 https://codesti.com/issue/codemirror/codemirror.next/813
https://github.com/codemirror/dev/issues/859
https://github.com/codemirror/lang-example/issues/3

I have cleared and re-installed all npm packages as well as run npm dedupe.
I am using the component exactly like your example in gitlab.

**Comment by SomaticIT** [comment]
Hello,

If your are using `vite` or `sveltekit` please refer to the documentation (https://github.com/touchifyapp/svelte-codemirror-editor#usage-with-vite--svelte-kit).

If not, can you give me the toolchain you use to build/run your project?

Thanks,

**Comment by DaleSparrow** [comment]
Hi! Thanks for the reply.

I did follow the sveltekit instructions in the documentation and my svelte.config.js file looks as follows:

```
import adapter from '@sveltejs/adapter-static';

export default {
	kit: {
		adapter: adapter({
			// default options are shown
			pages: 'build',
			assets: 'build',
			fallback: null,
			precompress: false
		}),
		
		
	},
	optimizeDeps: {
		include:["earclip"],
		exclude: ["codemirror", "@codemirror/language-javascript" /* ... */],
	}

};
```

let me know if I can give you any other info!

Kind Regards

Dale

**Comment by SomaticIT** [comment]
Hello,
if you are using the latest version `sveltekit`, you may move the config into the `vite.config.js`.
Depending on the extensions you use, you have to add more dependencies in the `exclude` key.

Here are some modules that can be added:
```
"codemirror",
"@codemirror/autocomplete",
"@codemirror/commands",
"@codemirror/lang-css",
"@codemirror/lang-html",
"@codemirror/lang-javascript",
"@codemirror/language",
"@codemirror/state",
"@codemirror/view",
```

**Comment by DaleSparrow** [comment]
Thank you! I will try it as soon as I'm back and let you know if it worked.
