### ISSUE TITLE
Unknown file extension ".svelte"

### ISSUE THREAD

**Issue by Tam2** [touchifyapp/svelte-codemirror-editor#8]
I seem to be having issues getting this package to work once built

My `vite.config.ts`

```
import { sveltekit } from '@sveltejs/kit/vite';
import type { UserConfig } from 'vite';

const config: UserConfig = {
	plugins: [sveltekit()],
	build: {
		rollupOptions: {
			external: [
				'codemirror',
				'svelte-codemirror-editor',
				'@codemirror/lang-javascript',
				'@codemirror/theme-one-dark'
			]
		}
	}
};

export default config;

```

The project builds successfully but when navigating on to a page i get a few errors:

`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for C:\admin\node_modules\svelte-codemirror-editor\CodeMirror.svelte`

`TypeError: Failed to resolve module specifier "@codemirror/lang-javascript". Relative references must start with either "/", "./", or "../".`

**Comment by SomaticIT** [comment]
Hello,

Sorry for our late response.
Did you succeed to make it work?

Thanks
