### ISSUE TITLE
Setting `value` prop immediately after component initialization may not work

### ISSUE THREAD

**Issue by Lifulifu** [touchifyapp/svelte-codemirror-editor#9]
## Expected behavior:
CodeMirror should always render the value of `value` prop.

## Bug
Under rare circumstances, the value of `value` may not match what is rendered. 
For example, the final value that is rendered in CodeMirror should be "second", but can sometimes be "first".

```
<script>
let value = "first";
onMount(() => {
    value = "second"
})
</script>

<CodeMirror bind:value />
```

This bug can be solved by not returning on this [line](https://github.com/touchifyapp/svelte-codemirror-editor/blob/7fe51e9fab20ffda750a742f4da2eb9d7be550f2/src/lib/CodeMirror.svelte#L88), so that editor state is always updated when `value` changes. 

This bug may be caused by this [line](https://github.com/touchifyapp/svelte-codemirror-editor/blob/7fe51e9fab20ffda750a742f4da2eb9d7be550f2/src/lib/CodeMirror.svelte#L52), if `view` and `value` change at the same tick, the second change of `value` may be marked as the first change and update is skipped.

**Comment by SomaticIT** [comment]
Hello,

Sorry for my late response.

I'm not sure we can fully disable the `debounce` behavior because when value change, the entire context need to be redrawn.
An option could be to add an option to disable this behavior when you have full control on your performances.

What do you think?

**Comment by SomaticIT** [comment]
Hello @Lifulifu,

Thank you for reporting this issue.
We added a new option `nodebounce` in `v1.2.0`.

You can now do:
```svelte
<CodeMirror bind:value nodebounce />
```
